name: Lint

on: push

jobs:
  run:
    name: Lint on Python
    runs-on: "ubuntu-22.04"

    steps:
      - uses: actions/checkout@v3

      - name: Check for CRLF endings
        uses: erclu/check-crlf@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install hatch
        run: python -m pip install -U pip hatch

      - name: Lint
        run: hatch run lint:style
